myAwesomeVar=myVar
wonderVar=oasis
compiler=g++

test:
	this is a testing command
	another command

emptyTarget:

wonderfulTarget:
	myLittleAwesome
	funny!! hahahaha

WhatDoesTheProgrammerSay:
	I Love Program Engineering!
	WOW!
	very diagrams
	much UML
